// Auto-generated by upload-to-cloudflare.ts
// Last updated: 2025-11-11T15:07:14.012Z

const IMAGE_IDS: Record<string, string> = {
  'banner01.png': 'banner01',
  'doctor-jiyun.jpg': 'doctor-jiyun',
  'doctor-minho.jpg': 'doctor-minho',
  'doctor-portrait.jpg': 'doctor-portrait',
  'doctor-yujun-real.png': 'doctor-yujun-real',
  'doctor-yujun.jpg': 'doctor-yujun',
  'doctor1.png': 'doctor1',
  'doctor2.png': 'doctor2',
  'doctor3.png': 'doctor3',
  'font_desk.png': 'font_desk',
  'header_logo.png': 'header_logo',
  'header_logo_white.png': 'header_logo_white',
  'hero-clinic.jpg': 'hero-clinic',
  'philosophy_section.png': 'philosophy_section',
  'reception-banner.png': 'reception-banner',
  'space/brushing-room.png': 'space-brushing-room',
  'space/clinic-hallway.png': 'space-clinic-hallway',
  'space/front-desk.png': 'space-front-desk',
  'space/private-treatment-room.png': 'space-private-treatment-room',
  'space/waiting-lounge.png': 'space-waiting-lounge',
  'space-interior.jpg': 'space-interior',
  'team-care.png': 'team-care',
  'team-philosophy.jpg': 'team-philosophy',
  'treatment-aesthetic.jpg': 'treatment-aesthetic',
  'treatment-detail.jpg': 'treatment-detail',
  'treatment-general.jpg': 'treatment-general',
  'treatment-gum.jpg': 'treatment-gum',
  'treatment-implant.jpg': 'treatment-implant',
};

export default IMAGE_IDS;
